/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void led_state_clear(uint32_t* output_data_address){
	for(int led = 12; led < 16; led++){
	*output_data_address &= ~(1 << led);
	}
}

void led_state_oppositer(uint32_t* output_data_address, int led){
	if (led == 12 || led == 13 || led == 14 || led == 15){
		uint32_t temp = *output_data_address;
		temp &= 1 << led;
		temp = ~(temp >> led);
		temp &= 1;
		*output_data_address &= ~(1 << led);
		*output_data_address |= (temp << led);
	}
	else{
		printf("led_state_oppositer: LED number %d is invalid.\n", led);
	}
}


int main(void)
{
    uint32_t* RCC_GPIOD_address = (uint32_t*) 0x40023830;
    uint32_t* GPIOD_mode_address = (uint32_t*) 0x40020C00;
    uint32_t* GPIOD_output_data_address = (uint32_t*) 0x40020C14;

    *RCC_GPIOD_address |= 1 << 3;

    *GPIOD_mode_address &= ~(3 << 24);
    *GPIOD_mode_address |= 1 << 24;

    *GPIOD_mode_address &= ~(3 << 26);
    *GPIOD_mode_address |= 1 << 26;

    *GPIOD_mode_address &= ~(3 << 28);
    *GPIOD_mode_address |= 1 << 28;

    *GPIOD_mode_address &= ~(3 << 30);
    *GPIOD_mode_address |= 1 << 30;

    led_state_clear(GPIOD_output_data_address);

    for (int i = 0; i < 10; i++){
    led_state_oppositer(GPIOD_output_data_address, 12);
    led_state_oppositer(GPIOD_output_data_address, 13);
    led_state_oppositer(GPIOD_output_data_address, 14);
    led_state_oppositer(GPIOD_output_data_address, 15);
    }

    led_state_clear(GPIOD_output_data_address);

	for(;;);
}
