/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void led_state_clear(uint32_t* output_data_address){
	for(int led = 12; led < 16; led++){
	*output_data_address &= ~(1 << led);
	}
}

void led_state_oppositer(uint32_t* output_data_address, int led){
	if (led == 12 || led == 13 || led == 14 || led == 15)
	{
	uint32_t temp = *output_data_address;
	temp &= 1 << led;
	temp = ~(temp >> led);
	temp &= 1;
	*output_data_address &= ~(1 << led);
	*output_data_address |= (temp << led);
	}
	else
	{
		printf("led_state_oppositer: LED number %d is invalid.\n", led);
	}
}

void led_state_true(uint32_t* output_data_address, int led){
	if (led == 12 || led == 13 || led == 14 || led == 15)
		*output_data_address |= (1 << led);
	else
	{
		printf("led_state_true: LED number %d is invalid.\n", led);
	}
}

void led_state_false(uint32_t* output_data_address, int led){
	if (led == 12 || led == 13 || led == 14 || led == 15)
		*output_data_address &= ~(1 << led);
	else
	{
		printf("led_state_false: LED number %d is invalid.\n", led);
	}
}

int main(void)
{
    uint32_t* RCC_address = (uint32_t*) 0x40023830;
    uint32_t* GPIOD_mode_address = (uint32_t*) 0x40020C00;
    uint32_t* GPIOD_output_data_address = (uint32_t*) 0x40020C14;

    uint32_t* GPIOA_mode_address = (uint32_t*) 0x40020000;
    uint32_t* GPIOA_input_data_address = (uint32_t*) 0x40020010;


    *RCC_address |= 1 << 3; // GPIOD
    *RCC_address |= 1 << 0; // GPIOA

    *GPIOD_mode_address &= ~(3 << 24);
    *GPIOD_mode_address |= 1 << 24;

    *GPIOD_mode_address &= ~(3 << 26);
    *GPIOD_mode_address |= 1 << 26;

    *GPIOD_mode_address &= ~(3 << 28);
    *GPIOD_mode_address |= 1 << 28;

    *GPIOD_mode_address &= ~(3 << 30);
    *GPIOD_mode_address |= 1 << 30;


    *GPIOA_mode_address &= ~(3 << 0);
    *GPIOA_mode_address |= 1 << 0;

    uint32_t status = (*GPIOA_input_data_address & 0x1);

    led_state_clear(GPIOD_output_data_address);

    while(1){
    	status = (*GPIOA_input_data_address & 0x1);

    	if(status)
    		led_state_true(GPIOD_output_data_address, 15);

    	else{
    		led_state_false(GPIOD_output_data_address, 15);
    	}

    }

}
